repo: 'confectionery-website-prototype'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-10
  - html
  - google-fonts
  - html-good-semantics
  - img-flex
  - css
  - border-box
  - responsive-css
  - responsive-font-sizes
  - nav-hover

html:
  - path: 'index.html'
    has:
      - 'img'
      - 'h2'
      - 'div'

css:
  - path: 'css/main.css'
    search:
      - 'padding'
      - 'margin'
      - 'position: relative'
      - 'position: absolute'
      - 'float: (left|right)'
      - 'display: block'
      - 'display: inline-block'
